<?php
return [
    [
        'category'=>['Поэма'],
        'slug' => 'mertvye-dushi',
        'id'=> 1,
        'name'=>'Мертвые души',
        'author'=>['Гоголь'],
        'year'=>'1842',
        'description'=>'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi, accusantium facilis harum et perspiciatis ullam non illo placeat quas eius eveniet voluptate voluptates libero delectus? Perferendis nesciunt iusto quis quia.',
        'image'=>'images/dead souls.jpg',
    ],
    [
        'category'=>['Повесть'],
        'slug' => 'palata-№6',
        'id'=> 2,
        'name'=>'Палата №6',
        'author'=>['Чехов'],
        'year'=>'1892',
        'description'=>'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi, accusantium facilis harum et perspiciatis ullam non illo placeat quas eius eveniet voluptate voluptates libero delectus? Perferendis nesciunt iusto quis quia.',
        'image'=>'images/palata6.jpg',
    ],
    [
        'category'=>['Литература ужасов'],
        'slug' => 'zov-ktulhu',
        'id'=> 3,
        'name'=>'Зов Ктулху',
        'author'=>['Лавкрафт'],
        'year'=>'1928',
        'description'=>'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi, accusantium facilis harum et perspiciatis ullam non illo placeat quas eius eveniet voluptate voluptates libero delectus? Perferendis nesciunt iusto quis quia.',
        'image'=>'images/zov ktulhu.png',
    ],
    [
        'category'=> ['Научная фантастика', 'Роман'],
        'slug' => 'piknik-na-obochine',
        'id'=> 4,
        'name'=>'Пикник на обочине',
        'author'=>['Аркадий Стругацкий', 'Борис стругацкий'],
        'year'=>'1972',
        'description'=>'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi, accusantium facilis harum et perspiciatis ullam non illo placeat quas eius eveniet voluptate voluptates libero delectus? Perferendis nesciunt iusto quis quia.',
        'image'=>'images/stalker.jpg',
    ],
    [
        'category'=>['Роман'],
        'slug' => 'zolotoj-telyonok',
        'id'=> 5,
        'name'=>'Золотой телёнок',
        'author'=>['Илья Арнольдович Ильф', 'Евгений Петрович Петров'],
        'year'=>'1931',
        'description'=>'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi, accusantium facilis harum et perspiciatis ullam non illo placeat quas eius eveniet voluptate voluptates libero delectus? Perferendis nesciunt iusto quis quia.',
        'image'=>'images/telenok.jpg',
    ],
];